protobuf_sources()

python_distribution(
    name="dist",
    dependencies=[
        ":type",
                  ],
    provides=python_artifact(
        name="google-types-proto",
        version="0.0.1",
    ),
)
